version: '3.8'

services:
  whisper-web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MODE=web
      - WORKERS=4  # Enable multithreading with 4 workers
      - HOST=0.0.0.0
      - PORT=8000
      - TRANSCRIPTION_API_KEY=${TRANSCRIPTION_API_KEY:-}
    volumes:
      - whisper_cache:/root/.cache/whisper
      - ./storage:/app/storage  # Persist async task storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  # Optional: Single-threaded mode for comparison
  whisper-web-single:
    build: .
    ports:
      - "8001:8000"
    environment:
      - MODE=web
      - WORKERS=1  # Single-threaded mode
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - whisper_cache:/root/.cache/whisper
      - ./storage:/app/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    profiles:
      - single  # Only start with --profile single

volumes:
  whisper_cache:
    driver: local