version: '3.8'

services:
  whisper-web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MODE=web
      - WORKERS=8  # Higher worker count for production
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - whisper_cache:/root/.cache/whisper
      - ./storage:/app/storage
      - ./logs:/app/logs  # Log directory
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 45s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
        reservations:
          cpus: '2.0'
          memory: 4G
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  # Load balancer (optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - whisper-web
    restart: unless-stopped
    profiles:
      - loadbalancer

  # Monitoring (optional)
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped
    profiles:
      - monitoring

volumes:
  whisper_cache:
    driver: local