---
name: Build and Push Docker Images

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-24.04
            docker-platform: linux/amd64
            cache-scope: linux-amd64
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
            docker-platform: linux/arm64
            cache-scope: linux-arm64

    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx (Linux)
        if: startsWith(matrix.platform, 'linux')
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch,suffix=-${{ matrix.cache-scope }}
            type=ref,event=pr,suffix=-${{ matrix.cache-scope }}
            type=semver,pattern={{version}},suffix=-${{ matrix.cache-scope }}
            type=semver,pattern={{major}}.{{minor}},suffix=-${{ matrix.cache-scope }}
            type=semver,pattern={{major}},suffix=-${{ matrix.cache-scope }}
            type=raw,value=latest-${{ matrix.cache-scope }},enable={{is_default_branch}}
          flavor: |
            latest=false

      - name: Build and push Docker image (Linux)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.docker-platform }}
          push: ${{ github.event_name != 'pull_request' }}
          load: ${{ github.event_name == 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=gha,scope=${{ matrix.cache-scope }}
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache-${{ matrix.cache-scope }}
          cache-to: |
            type=gha,mode=max,scope=${{ matrix.cache-scope }}
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache-${{ matrix.cache-scope }},mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          target: final

      - name: Test Docker image
        run: |
          IMAGE_TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n 1)
          echo "Testing image: $IMAGE_TAG"
          if [[ "${{ github.event_name }}" != "pull_request" ]]; then
            docker pull $IMAGE_TAG
          fi
          docker tag $IMAGE_TAG whisper-cli:test
          docker run --rm whisper-cli:test --help
          echo "Testing model loading..."
          echo "test" | docker run --rm -i whisper-cli:test --model tiny --no-stream || echo "Expected to fail without valid audio"

      - name: Test wrapper script
        run: |
          chmod +x transcribe
          ./transcribe || echo "Help displayed successfully"

  create-manifest:
    if: github.event_name != 'pull_request'
    needs: build-and-test
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push multi-arch manifest
        run: |-
          BASE_TAG="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            docker buildx imagetools create -t ${BASE_TAG}:latest \
              ${BASE_TAG}:latest-linux-amd64 \
              ${BASE_TAG}:latest-linux-arm64
          fi
          if [[ "${{ github.ref_type }}" == "branch" ]]; then
            BRANCH_NAME=$(echo ${{ github.ref_name }} | tr '/' '-')
            docker buildx imagetools create -t ${BASE_TAG}:${BRANCH_NAME} \
              ${BASE_TAG}:${BRANCH_NAME}-linux-amd64 \
              ${BASE_TAG}:${BRANCH_NAME}-linux-arm64
          fi
          if [[ "${{ github.ref_type }}" == "tag" && "${{ github.ref_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            TAG="${{ github.ref_name }}"
            MAJOR=$(echo $TAG | cut -d. -f1)
            MINOR=$(echo $TAG | cut -d. -f1,2)
            docker buildx imagetools create -t ${BASE_TAG}:${TAG} ${BASE_TAG}:${TAG}-linux-amd64 ${BASE_TAG}:${TAG}-linux-arm64
            docker buildx imagetools create -t ${BASE_TAG}:${MINOR} ${BASE_TAG}:${MINOR}-linux-amd64 ${BASE_TAG}:${MINOR}-linux-arm64
            docker buildx imagetools create -t ${BASE_TAG}:${MAJOR} ${BASE_TAG}:${MAJOR}-linux-amd64 ${BASE_TAG}:${MAJOR}-linux-arm64
          fi

