name: Test Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux/amd64
          - os: macos-latest  
            platform: linux/arm64
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: ${{ matrix.platform }}
        load: true
        tags: whisper-cli:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Test Docker image
      run: |
        # Test help output
        docker run --rm whisper-cli:test --help
        
        # Test model loading (without actual audio)
        echo "Testing model loading..."
        echo "test" | docker run --rm -i whisper-cli:test --model tiny --no-stream || echo "Expected to fail without valid audio"
    
    - name: Test wrapper script
      run: |
        # Make script executable
        chmod +x transcribe
        
        # Test help
        ./transcribe || echo "Help displayed successfully"